version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  # different jobs are calles later in the workflows sections

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: "cimg/node:14.15"        
    steps:
      - node/install:
          node-version: '14.15'  
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install
  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - run:
          name: Test FrontEnd
          # TODO: Install, build, deploy in both apps
          command: |
            echo "# TODO: Testing FrontEnd"
  deploy:
    docker:
      - image: cimg/<language>:<version TAG>
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: my-deploy-commands

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build